require('configs.themer')
require('configs.telescope')
require('configs.lsp-zero')
require('configs.lualine')
require('configs.refactoring')
require('configs.aerial')
require('configs.nvim-treesitter')
